### PR TITLE
Allowing users to receive PublicKey and PrivateKey as JSON String

### PR DESCRIPTION
**Pull request by tpmccallum**
I noticed this request/issue < #89 > , by @drbh , which mentioned being able to serialize and deserialize recrypt data structures (to store on disk etc.)

I have updated both recrypt-rs and gridiron so that they both implement serde as an optional feature. Users/calling-code can choose to take advantage of the feature in the event that they want to be able to read and write the PrivateKey and PublicKey fields to disk (or return these values back to the calling code etc.)

Please see the other PR at https://github.com/IronCoreLabs/recrypt-rs/pull/109 which goes hand in hand with this PR

### CODE REVIEW

**Comment by tpmccallum** [comment]
Also ran the cargo test on this branch with the following results
```
test result: ok. 93 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests gridiron
```

**Comment by clintfred** [comment]
Thanks for the contribution!

I have opened #32 to address the failing OSX CI jobs. It looks like `cargo fmt` is also failing.

**Comment by clintfred** [comment]
CI failures have been fixed with #33. Feel free to rebase on top of master to pick up that fix.

**Comment by tpmccallum** [comment]
All tests passing now. 
I will keep an eye out for the merge of this PR because I will need to tweak the recrypt-rs dependencies in [the related recrypt-rs PR](https://github.com/IronCoreLabs/recrypt-rs/pull/109) from 
```
gridiron = { git= "https://github.com/tpmccallum/gridiron", branch = "optional_serde_feature", version = "~0.7.0", features = ["serde"], default-features = false }
```
to
```
gridiron = { version = "~0.7.0", features = ["serde"] }
```
Any and all feedback is most welcome.
Thanks so much.

**Comment by tpmccallum** [comment]
This PR may not be required as per [this recrypt conversation](https://github.com/IronCoreLabs/recrypt-rs/pull/109#issuecomment-620308010).

Happy for this to be closed.

**Pull request closed without merging**
